spring:
  application:
    name: book-service
  datasource:
    url: 'jdbc:postgresql://localhost:5432/bd-lavagem-automovel'
    username: 'postgres'
    password: '6655'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
